### ISSUE TITLE
[ember-cli 2.2.0-beta.1] mocha.setup is not a function

### ISSUE THREAD

**Issue by ballPointPenguin** [switchfly/ember-cli-mocha#94]
Using a fresh install of ember-cli v2.2.1-beta.1 and running
```
ember install ember-cli-mocha
ember test
```
the project builds and then stalls without running the tests

running the server and opening http://localhost:4200/tests shows some errors, starting with:
```
Uncaught TypeError: mocha.setup is not a function                    mocha-setup.js:1
```

This works as expected when using ember-cli 13.13.

Cross-posted at https://github.com/ember-cli/ember-cli/issues/5224

**Comment by rwjblue** [comment]
Duplicate of https://github.com/switchfly/ember-cli-mocha/issues/93

**Comment by mkempe** [comment]
Fix (works with  2.2.0-beta.2), see #95

**Comment by rwjblue** [comment]
Closing in favor of #93, #95, and https://github.com/ember-cli/ember-cli/pull/5274.
